#-------------->their we import turtle
import turtle
#-------------->their we rename our turtle to p
p=turtle.Turtle()
#-------------->code starts their
p.begin_fill()
# p.speed(0.6)
p.color("blue")
p.left(90)
p.forward(100)
p.left(90)
p.forward(100)
p.left(90)
p.forward(100)
p.left(90)
p.forward(50)
p.right(90)
p.forward(5)
p.right(90)
p.forward(70)
p.left(90)
p.forward(100)
p.left(90)
p.forward(60)
p.left(90)
p.forward(50)
p.right(90)
p.forward(60)
p.left(90)
p.forward(70)
p.end_fill()
#------------------>second
p.begin_fill()
p.color("yellow")
p.left(-90)
p.forward(40)
p.right(90)
p.forward(110)
p.right(90)
p.forward(50)
p.left(90)
p.forward(5)
p.left(90)
p.forward(40)
p.right(90)
p.forward(80)
p.right(90)
p.forward(120)
p.right(90)
p.forward(80)
p.end_fill()
#-------------->their we done our program
turtle.done()